routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){

Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);

});

Route::get('/about', 'PagesController@about');
Route::get('/services', 'PagesController@services');
Route::get('/index', 'PagesController@index');
Route::get('/messages', 'PostsController@messages');

Route::post('/messages', 'MessageController@create');


Route::resource('posts', 'PostsController');


Route::any('users/{id}', function ($id) {
    
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function roles() {

        return $this->belongsToMany('App\Role');


    }


    public function hasAnyRoles($roles){


        if($this->roles()->whereIn('name', $roles)->first()){

            return true;

        }

        return false;

    }

    public function hasRole($role){


        if($this->roles()->where('name', $role)->first()){

            return true;

        }

        return false;

    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Role;
use Gate;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UsersController extends Controller
{


public function _construct(){


$this->middleware('auth');


}

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $users = User::all();
        return view ('admin.users.index')->with('users', $users);


    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {

        if(Gate::denies('edit-users')) {

            return redirect(route('admin.users.index'));
        }

    $roles= Role::all();
    return view('admin.users.edit')->with([

        'user' => $user,
        'roles' => $roles

    ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return void
     */
    public function update(Request $request, User $user)
    {


        $user->roles()->sync($request->roles);

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {

        if(Gate::denies('delete-users')) {

            return redirect(route('admin.users.index'));
        }

        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit User {{$user->name}}</div>

                    <div class="card-body">


                        <form action="{{route('admin.users.update', $user)}}" method="POST">
                            @csrf
                            {{method_field('PUT')}}

                            @foreach($roles as $role)
                                    <div class="form-check">
                                        <input type="checkbox" name="roles[]" value="{{ $role->id }}" @if($user->roles->contains($role->id)) checked=checked @endif/>
                                        <label> {{$role->name}}</label>
                                    </div>


                                @endforeach

                            <button type="submit" class="btn btn-primary">
                                Update

                            </button>




                        </form>









                    </div>



                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Users</div>

                <div class="card-body">


                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">User Name</th>
                                <th scope="col">User Email</th>
                                <th scope="col">Roles</th>
                                <th scope="col">Actions</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                            <tr>
                                <th scope="row">{{$user->id}}</th>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{ implode(', ', $user->roles->pluck('name')->toArray())}}</td>

                                <td>
                                    @can('edit-users')
                                  <a href="{{route('admin.users.edit', $user->id)}}">  <button type="button" class="btn btn-primary" class="float-left">Edit</button> </a>
                                    @endcan

                                    @can('delete-users')
                                  <form action="{{route('admin.users.destroy', $user)}}"  method="POST" class="float-left">
                                      @csrf
                                      {{method_field('DELETE')}}
                                      <button type="submit" class="btn btn-danger" >Delete</button></a>
                                  </form>
                                        @endcan
                                </td>
                            </tr>
                    @endforeach

                            </tbody>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection